### ISSUE TITLE
[CSNG] Custom brightness control script / Not responding slider in Pre4

### ISSUE THREAD

**Issue by rubenverhoef** [opencardev/crankshaft#178] opened 2018-07-23 10:33 UTC
It would be nice if a user made brightness control script/command is launched every time the brightness changed with the brightness value as an argument.

So i can make a script with `gpio pwm 26 "brightness value"`

see #176

**Comment by hawkeyexp** [comment] 2018-07-24 20:14
Will be available with pre4.

**Comment by hawkeyexp** [comment] 2018-08-03 18:11
Pre4 is available this weekend including the feature.

**Comment by osokthedevil** [comment] 2018-08-06 06:29
for some reason i can't even adjust the brightness with the latest update? using this display that worked in older versions that i can adjust the display brightness. https://www.amazon.ca/gp/product/B014WKCFR4/ref=oh_aui_detailpage_o01_s00?ie=UTF8&psc=1

**Comment by hawkeyexp** [comment] 2018-08-06 08:41
@osokthedevil enable debug mode in settings, reboot, adjust brightness, create debug log and add here please.

**Comment by osokthedevil** [comment] 2018-08-06 16:06
sorry @hawkeyexp dumb question but how do i extract the log file?

**Comment by osokthedevil** [comment] 2018-08-06 16:08
[debug.zip](https://github.com/opencardev/crankshaft/files/2263278/debug.zip)

**Comment by hawkeyexp** [comment] 2018-08-06 16:09
you can grab it from sd /boot/debug.zip or connect via ssh to copy it somewhere

**Comment by osokthedevil** [comment] 2018-08-06 16:10
sorry haven't finished my first cup off coffee. debug.zip file dropped for you

**Comment by osokthedevil** [comment] 2018-08-06 16:25
ya doesn't move at all. everything else responds to touch but the slider for some reason.

**Comment by hawkeyexp** [comment] 2018-08-06 16:30
Same on day and night ? Try to switch to night (auto switching back is only every minute) and test it there please - currently i have not really an idea...

**Comment by osokthedevil** [comment] 2018-08-06 16:33
yes day or night mode no change, ya a little weird. I was using crankshaft -2018-03-13 before i updated yesterday. i know that one works fine with the display. Hopefully that helps you out some what.

**Comment by hawkeyexp** [comment] 2018-08-06 16:37
Please let me know if your system creates the file /tmp/custombrightness

**Comment by osokthedevil** [comment] 2018-08-06 16:42
no file found. It also says in the settings under - custom brightness command = disabled

**Comment by hawkeyexp** [comment] 2018-08-06 16:55
Please check if a direct control is working via shell as pi user:

this should set max brightness:
`echo 255 > /sys/class/backlight/rpi_backlight/brightness`
this should set dark brightness:
`echo 55 > /sys/class/backlight/rpi_backlight/brightness`

**Comment by osokthedevil** [comment] 2018-08-06 17:00
will do so. I just tested the release before the new one, 2018-07-13-crankshaft-ng-9B0FBA9.zip and the brightness adjustment works. going to reload the new release and check those settings

**Comment by osokthedevil** [comment] 2018-08-06 17:31
okay so running the echo commands works for day and night adjustment. At least give me some what of the ability to adjust the brightness at the moment.

**Comment by osokthedevil** [comment] 2018-08-06 17:37
[debug.zip](https://github.com/opencardev/crankshaft/files/2263502/debug.zip)

here is a new debug.zip file for your viewing

**Comment by hawkeyexp** [comment] 2018-08-06 19:03
There seems to be no prob i can identify currently.

**Comment by osokthedevil** [comment] 2018-08-06 19:07
okay, i don't know what else i can say beside 07 13 version brightness slider works fine and 08 03 it doesn't.

**Comment by hawkeyexp** [comment] 2018-08-06 19:16
I'm sorry at the moment - it is the first feedback about a brightness prob currently - i keep an eye on it.

**Comment by hawkeyexp** [comment] 2018-08-06 20:02
I have update the management tool to collect some more info.
You can update it with `crankshaft update csmt` in shell (you need internet access)
After update (1.1.4) you can create a new debug log. Possible it gives a better result.

**Comment by osokthedevil** [comment] 2018-08-06 20:27
Crankshaft Management Tool v1.0.9 is executing command...

New file:
Current file: 8f402dcabf5e78b6829e8db2c8e9926f
ABORT: checksum fail.
pi@crankshaft:~ $

**Comment by hawkeyexp** [comment] 2018-08-06 20:37
Try later sometimes github needs a bit to resync - but a note - debug mode has no dns access - do it in dev mode.

**Comment by lockeandev** [comment] 2018-08-07 06:06
Same problem confirmed, brightness slider worked on Pre3 but not responsive in Pre4

**Comment by hawkeyexp** [comment] 2018-08-07 12:40
Here is a preview of next build including a slider fix which should work - please try out and report back. Thx.

[https://drive.google.com/file/d/1ZvIEtntpNv3t4zlDqPSyb_2HypJH1Ck4/view?usp=sharing](url)

**Comment by hawkeyexp** [comment] 2018-08-08 18:38
@osokthedevil does the preview fix your problem?

**Comment by osokthedevil** [comment] 2018-08-08 18:52
Sorry I haven't tried. Plus my knowledge is limited to even the debug and using that as well. I'm finished Holiday so been busy at work

**Comment by osokthedevil** [comment] 2018-08-09 02:05
@hawkeyexp downloading now, i will let you know in a bit.

**Comment by osokthedevil** [comment] 2018-08-09 03:37
@hawkeyexp brightness is working properly now

**Comment by osokthedevil** [comment] 2018-08-09 03:48
@hawkeyexp love the wifi add ins

**Comment by hawkeyexp** [comment] 2018-08-14 10:49
slider is fixed custom brightness, too -> closing.

**Closed by hawkeyexp** 2018-08-14 10:49 UTC
Labels: Fixed/Released, bug, crankshaft-ng, custom-hardware, enhancement
