### ISSUE TITLE
[csng] openauto will not start after the one-time start of Dev Mode

### ISSUE THREAD

**Issue by Bigleby** [opencardev/crankshaft#153] opened 2018-07-07 19:25 UTC
I have a Raspberry Pi 2B and i installed the newest Version (2018-07-01/C22D7B).
After the first boot, i changed the mode to dev mode and installed the driver for my Display. After that step i changed the mode to DevMode0 but the system didn´t start in the Openauto App

**Comment by hawkeyexp** [comment] 2018-07-09 05:09
Sounds like your "driver" has changed something.
Add Info about Display, driver etc.

**Comment by Bigleby** [comment] 2018-07-09 16:39
The Display is a 5 inch Raspberry Pi Display and the driver can be found here: 
https://github.com/goodtft/LCD-show
it´s the LCD5-show driver and i installed him with following commands:
sudo apt-get install git
git clone https://github.com/goodtft/LCD-show.git
chmod +R 755 LCD-show
cd LCD-show/
sudo ./LCD5-show

**Comment by hawkeyexp** [comment] 2018-07-09 17:47
Please don't use this installer with CS-NG cause it does an override of files and not upgrading mssing entries needed for the display in cmdline.txt config.txt inittab etc. By it's design it can kill EVERY custom system setup - that's the reason why i hate those displays and it's drivers :-)
You have a chance if you check what exactly is needed and add it manually in the files.
It's no problem caused by CS-NG so i will close the issue.

**Closed by hawkeyexp** 2018-07-09 17:47 UTC
Labels: crankshaft-ng, custom-hardware, more-info-needed

**Comment by Bigleby** [comment] 2018-07-09 17:51
Thank you

**Comment by Bigleby** [comment] 2018-07-09 18:13
I only had to modify the config.txt 

here is the new  file maybe someone need it, for this kind of display too.
``# For more options and information see
# http://rpf.io/configtxt
# Some settings may impact device functionality. See link above for details

# uncomment if you get no picture on HDMI for a default "safe" mode
#hdmi_safe=1

# uncomment this if your display has a black border of unused pixels visible
# and your display can output without overscan
#disable_overscan=1

# uncomment the following to adjust overscan. Use positive numbers if console
# goes off screen, and negative if there is too much border
#overscan_left=16
#overscan_right=16
#overscan_top=16
#overscan_bottom=16

# uncomment to force a console size. By default it will be display's size minus
# overscan.
#framebuffer_width=1280
#framebuffer_height=720

# uncomment if hdmi display is not detected and composite is being output
hdmi_force_hotplug=1

# uncomment to force a specific HDMI mode (this will force VGA)
#hdmi_group=1
#hdmi_mode=1

# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes
#hdmi_drive=2

# uncomment to increase signal to HDMI, if you have interference, blanking, or
# no display
#config_hdmi_boost=4

# uncomment for composite PAL
#sdtv_mode=2

#uncomment to overclock the arm. 700 MHz is the default.
#arm_freq=800

# Uncomment some or all of these to enable the optional hardware interfaces
dtparam=i2c_arm=on
#dtparam=i2s=on
dtparam=spi=on
enable_uart=1
# Uncomment this to enable the lirc-rpi module
#dtoverlay=lirc-rpi

# Additional overlays and parameters are documented /boot/overlays/README

# Enable audio (loads snd_bcm2835)
dtparam=audio=on
max_usb_current=1
hdmi_force_hotplug=1
config_hdmi_boost=7
hdmi_group=2
hdmi_mode=1
hdmi_mode=87
hdmi_drive=1
hdmi_cvt 800 480 60 6 0 0 0
dtoverlay=ads7846,cs=1,penirq=25,penirq_pull=2,speed=50000,keep_vref_on=0,swapxy=0,pmax=255,xohms=150,xmin=200,xmax=3900,ymin=200,ymax=3900
# Disable the PWR LED.
dtparam=pwr_led_trigger=none
dtparam=pwr_led_activelow=off
``
